spring:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  application:
    name: my4cut

  profiles:
    active: local

server:
  port: 8080

jwt:
  token:
    secretKey: ${JWT_SECRET_KEY}
    expiration:
      access: 14400000
