server:
  port: 8080

spring:
  application:
    name: my4cut

  datasource:
    url: ${DB_URL}?useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # prod에서는 validate 또는 none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

jwt:
  token:
    secretKey: ${JWT_SECRET_KEY}

cloud:
  aws:
    region: ap-northeast-2
    s3:
      bucket: my4cut-image-bucket